import { Food } from './app/shared/model/Food'
import { Tag } from './app/shared/model/Tag'

export const sample_foods: Food[] = [
  {
    _id: '1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/images/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    _id: '2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/images/food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    _id: '3',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/images/food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    _id: '4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/images/food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    _id: '5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/images/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    _id: '6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/images/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    _id: '7',
    name: 'Spicy Cheese Burger',
    price: 12,
    cookTime: '20-30',
    favorite: false,
    origins: ['Indian'],
    stars: 4.0,
    imageUrl: 'assets/images/food-7.jpg',
    tags: ['FastFood', 'Burger', 'Lunch'],
  },
  {
    _id: '8',
    name: 'Vegetables Magento Pizza',
    price: 9,
    cookTime: '45-50',
    favorite: false,
    origins: ['indian'],
    stars: 4.0,
    imageUrl: 'assets/images/food-8.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
]

export const sample_tags: Tag[] = [
  { name: 'Tất cả', count: 8 },
  { name: 'Ăn nhanh', count: 4 },
  { name: 'Pizza', count: 3 },
  { name: 'Ăn trưa', count: 3 },
  { name: 'Ăn mặn', count: 2 },
  { name: 'Hamburger', count: 2 },
  { name: 'Chiên rán', count: 1 },
  { name: 'Súp', count: 1 },
]
